/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("pinpoint.java8-conventions")
}

dependencies {
    implementation("io.vertx:vertx-web:4.2.2")
}

description = "pinpoint-vertx-4-plugin-testweb"
