### LongConter, w/o tags, w/o interval
GET http://localhost:8080/systemMetric/chart.pinpoint?applicationName=hyunjoon.cho&hostName=AL01256785.local&metricName=mem&fieldName=free&from=1612158610000&to=1612158910000
Accept: application/json

### LongCounter, w/o tags, with interval
GET http://localhost:8080/systemMetric/chart.pinpoint?applicationName=hyunjoon.cho&hostName=AL01256785.local&metricName=mem&fieldName=free&from=1612158610000&to=1612158910000&interval=30
Accept: application/json

### DoubleCounter, w/o tags, with interval
GET http://localhost:8080/systemMetric/chart.pinpoint?applicationName=hyunjoon.cho&hostName=AL01256785.local&metricName=cpu&fieldName=usage_user&from=1612158610000&to=1612158910300&interval=50
Accept: application/json

### DoubleCounter, with tags, with interval
GET http://localhost:8080/systemMetric/chart.pinpoint?applicationName=hyunjoon.cho&hostName=AL01256785.local&metricName=cpu&fieldName=usage_user&tags=cpu:cpu1&from=1612158610000&to=1612158910000&interval=100
Accept: application/json

### with multiple tags > wrong behavior
GET http://localhost:8080/systemMetric/chart.pinpoint?applicationName=hyunjoon.cho&hostName=AL01256785.local&metricName=disk&fieldName=used_percent&tags=device:disk1s4,fstype:apfs,mode:rw,path:/private/var/vm&from=1612158610000&to=1612158910000&interval=30
Accept: application/json

### No Such Metric
GET http://localhost:8080/systemMetric/chart.pinpoint?applicationName=hyunjoon.cho&hostName=AL01256785.local&metricName=mem&fieldName=freer&from=1612158610000&to=1612158910000
Accept: application/json

### Wrong tags
GET http://localhost:8080/systemMetric/chart.pinpoint?applicationName=hyunjoon.cho&hostName=AL01256785.local&metricName=disk&fieldName=used_percent&tags=cpu:cpu1&from=1612158610000&to=1612158910000&interval=30
Accept: application/json

###
