### LongCounter, w/o tags
GET http://localhost:8080/systemMetric/list.pinpoint?applicationName=hyunjoon.cho&hostName=AL01256785.local&metricName=mem&fieldName=free&from=1612158610000&to=1612158910000
Accept: application/json

### DoubleCounter, w/o tags
GET http://localhost:8080/systemMetric/list.pinpoint?applicationName=hyunjoon.cho&hostName=AL01256785.local&metricName=cpu&fieldName=usage_user&from=1612158610000&to=1612158910000
Accept: application/json

### DoubleCounter, with tags
GET http://localhost:8080/systemMetric/list.pinpoint?applicationName=hyunjoon.cho&hostName=AL01256785.local&metricName=cpu&fieldName=usage_user&tags=cpu:cpu0&from=1612158610000&to=1612158910000
Accept: application/json

### No Such Metric
GET http://localhost:8080/systemMetric/list.pinpoint?applicationName=hyunjoon.cho&hostName=AL01256785.local&metricName=mem&fieldName=freer&from=1612158610000&to=1612158910000
Accept: application/json

###

