pinpoint.zookeeper.address={YOUR_RELEASE_ZOOKEEPER_ADDRESS}

# service lookup executor
collector.service.lookup.executor.corePoolSize=4
collector.service.lookup.executor.maxPoolSize=8
collector.service.lookup.executor.queueCapacity=1024