SELECT CATENTRY_ID
, PARTNUMBER
, BUSCHN_ID
, HEADNAME
, VENDOR_ID
, BRAND_KOR_NM
, BRAND_CD
, ITNCATENTRYNM
, DISP_TYPE_CD
, CATENTTYPE
, PRIOD_DLVR_YN
, DLVREXPNSCALCTYPE
, ADLT_GOODS_YN
, DCCP_EXCPT_YN
, CHC_CHILD_YN
, DEFSORT
, DEFSORTCNT
, JOIN_CNT
, SCORE
, CO_BUY_ID
, EVERYCPEXCPTYN
, CARDCHRGDCEXCPTYN
, LUMPSUMDCEXCPTYN
, MULTI_CD
, GOODEVALYN
, FC_GOODS_PROM_DC (B.BUSCHN_ID, FC_PARSER(‘$’||B.PRICEOFFERPRICE, #, ‘$’), B.CATENTRY_ID, B.MULTI_CD) FC_DC_VAL
, CATALOG_ID
, CATALOG_NM
, CAT1_CD
, CAT1_NAME
, CAT2_CD
, CAT2_NAME
, CAT3_CD
, CAT3_NAME
, CAT4_CD
, CAT4_NAME
, CAT5_CD
, CAT5_NAME
, INIT_REGI_DTTM
, ALLI_MALL_GOODS_CD
, DUTY_USE_DUR
, MM_RNTAL_PRC
, MIN_CNTRB_PFRATE
, CAT_NAME
, PRICEOFFERPRICE
, CARD_BNFT
, GIFT_BNFT
, CASE WHEN B.DISP_TYPE_CD = ‘$’
THEN FC_GET_PACK_DLVR_FEE(B.BUSCHN_ID, B.CATENTRY_ID, B.MULTI_CD, ?, FC_PARSER(‘$’||B.PRICEOFFERPRICE, #, ‘$’))
ELSE FC_GET_GOODS_DLVR_FEE(B.BUSCHN_ID, B.CATENTRY_ID, B.MULTI_CD, ?, FC_PARSER(‘$’||B.PRICEOFFERPRICE, #, ‘$’))
END DLVR_PRICE
, ‘$’ CO_CD
, ‘$’ DEVICE_CHN_ID
, DECODE) AS PRC_SORT
, ‘$’ AS ORDER_YN
FROM (SELECT CATENTRY_ID
, PARTNUMBER
, BUSCHN_ID
, HEADNAME
, VENDOR_ID
, BRAND_KOR_NM
, BRAND_CD
, ITNCATENTRYNM
, DISP_TYPE_CD
, CATENTTYPE
, PRIOD_DLVR_YN
, DLVREXPNSCALCTYPE
, ADLT_GOODS_YN
, DCCP_EXCPT_YN
, CHC_CHILD_YN
, DEFSORT
, DEFSORTCNT
, JOIN_CNT
, NVL AS SCORE
, CO_BUY_ID
, EVERYCPEXCPTYN
, CARDCHRGDCEXCPTYN
, LUMPSUMDCEXCPTYN
, MULTI_CD
, GOODEVALYN
, CATALOG_ID
, CATALOG_NM
, CAT1_CD
, CAT1_NAME
, CAT2_CD
, CAT2_NAME
, CAT3_CD
, CAT3_NAME
, CAT4_CD
, CAT4_NAME
, CAT5_CD
, CAT5_NAME
, INIT_REGI_DTTM
, ALLI_MALL_GOODS_CD
, DUTY_USE_DUR
, MM_RNTAL_PRC
, MIN_CNTRB_PFRATE
, SUBSTR-#) AS CAT_NAME
, FC_GOODS_PRC_DC (A.BUSCHN_ID, ?, NULL, A.CATENTRY_ID, A.MULTI_CD, NULL, NULL, ?) AS PRICEOFFERPRICE
, FC_GET_OFFER_CARDEVENT_BATCH (A.BUSCHN_ID, ?, SYSDATE, A.CATENTRY_ID, A.MULTI_CD, ?) AS CARD_BNFT
, ‘$’ AS GIFT_BNFT
FROM (SELECT
/*+ LEADING USE_NL(XD XM) INDEX */
XD.CATENTRY_ID
, XD.PARTNUMBER
, XD.BUSCHN_ID
, FC_HEADNM(XD.CATENTRY_ID) AS HEADNAME
, NVL (XD.VENDOR_ID, #) VENDOR_ID
, NVL (XD.BRAND_NM, ‘$’) BRAND_KOR_NM
, NVL (TO_CHAR (XD.BRAND_CD), ‘$’) BRAND_CD
, XD.NAME AS ITNCATENTRYNM
, NVL (XD.DISP_TYPE_CD, ‘$’) DISP_TYPE_CD
, NVL (XD.CATENTTYPE, ‘$’) CATENTTYPE
, NVL (XD.PRIOD_DLVR_YN, ‘$’) PRIOD_DLVR_YN
, NVL (XD.OUTGO_LOC_CD, ‘$’) OUTGO_LOC_CD
, NVL (XD.DLVR_WAY_CD1, ‘$’) DLVR_WAY_CD1
, NVL (XD.AGREE_DLINE, ‘$’) AGREE_DLINE
, NVL (XD.ADLT_GOODS_YN, ‘$’) ADLT_GOODS_YN
, NVL (XD.DCCP_EXCPT_YN, ‘$’) DCCP_EXCPT_YN
, NVL (XD.CHC_CHILD_YN, ‘$’) CHC_CHILD_YN
, NVL (XD.STYLE_MNG_YN, ‘$’) STYLE_MNG_YN
, XD.CLICK_NUM AS DEFSORT
, XD.RANK_QTY AS DEFSORTCNT
, XD.JOIN_CNT
, XD.STAR AS SCORE
, ‘$’ AS CO_BUY_ID
, NVL (XD.EVERYCPEXCPTYN, ‘$’) AS EVERYCPEXCPTYN
, NVL (XD.CARDCHRGDCEXCPTYN, ‘$’) AS CARDCHRGDCEXCPTYN
, NVL (XD.LUMPSUMDCEXCPTYN, ‘$’) AS LUMPSUMDCEXCPTYN
, XD.MULTI_CD
, NVL (XD.ALLI_MALL_GOODS_CD, ‘$’) AS ALLI_MALL_GOODS_CD
, NVL (XD.DUTY_USE_DUR, #) AS DUTY_USE_DUR
, NVL (XD.MM_RNTAL_PRC, #) AS MM_RNTAL_PRC
, ‘$’ AS GOODEVALYN
, XD.CATALOG_ID
, XD.CATALOG_NM
, XD.CAT1_CD
, XD.CAT1_NAME
, XD.CAT2_CD
, XD.CAT2_NAME
, XD.CAT3_CD
, XD.CAT3_NAME
, XD.CAT4_CD
, XD.CAT4_NAME
, XD.CAT5_CD
, XD.CAT5_NAME
, XD.INIT_REGI_DTTM
, XM.MIN_CNTRB_PFRATE
, NVL AS DLVREXPNSCALCTYPE
, DECODE || DECODE || DECODE || DECODE || XD.CAT5_NAME AS CAT_NAME
FROM XCATENTRY_DISP XD
, XMD_MD_PFRATE_MNG_DTL XM
WHERE XD.MDCD = XM.MD_CD(+)
AND XD.SALESTAT = ‘$’
AND CATENTTYPE NOT IN (‘$’, ‘$’)
AND XD.CATENTRY_ID IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
AND XD.FLAG <> ‘$’
AND XD.BUSCHN_ID = FC_GET_CHNCD (XD.CATENTRY_ID, ?)
AND DECODE = ‘$’
)A )B
WHERE #=#
AND # = CASE
WHEN DISP_TYPE_CD IN (#, #, #, #, #, #, #, #, #)
THEN #
WHEN FC_PARSER(‘$’||B.PRICEOFFERPRICE, #, ‘$’) <= #
THEN #
ELSE #
END
ORDER BY DEFSORTCNT ASC, INIT_REGI_DTTM DESC