pinot.heatmap.topic.count=1
pinot.heatmap.topic.prefix=heatmap-stat-
pinot.heatmap.topic.padding.length=2

# true: serve application heatmap from the agent table, application table is not needed.
# requires pinpoint.web.heatmap.agent.enabled=true
pinpoint.web.heatmap.application.use-agent-table=false

pinpoint.web.heatmap.agent.enabled=false
pinpoint.web.heatmap.agent.table.name=heatmapStat