/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("pinpoint.java7-toolchain")
}

dependencies {
    api(project(":pinpoint-agent-proxy-common"))
    api(project(":pinpoint-profiler"))
    compileOnly(project(":pinpoint-bootstrap-core"))
}

description = "pinpoint-agent-proxy-app-plugin"
