#!/bin/sh
export JAVA_OPTS="-Xms4G -Xmx8G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xlog:gc:logs/gc-pinot-controller.log"
"${PINOT_HOME}/bin/pinot-admin.sh" StartController -zkAddress zk:2181 -controllerPort 9000
