pinpoint.zookeeper.address={YOUR_LOCAL_ZOOKEEPER_ADDRESS}

# service lookup executor
collector.service.lookup.executor.corePoolSize=2
collector.service.lookup.executor.maxPoolSize=4
collector.service.lookup.executor.queueCapacity=512