export enum APP_SETTING_KEYS {
  FAVORLIITE_APPLICATION_LIST = 'pp.favoriteApplicationList',
  TIMEZONE = 'pp.timezone',
  DATE_FORMAT = 'pp.dateFormat',
  SPLIT_SIZE = 'pp.splitSize',
  LAYER_HEIGHT = 'pp.layerHeight',
  USER_DEFAULT_INBOUND = 'pp.userDefaultInbound',
  USER_DEFAULT_OUTBOUND = 'pp.userDefaultOutbound',
  USER_DEFAULT_PERIOD = 'pp.userDefaultPeriod',
  TRANSACTION_LIST_GUTTER_POSITION = 'pp.transactionListGutterPosition',
  CHART_NUM_PER_ROW = 'pp.chartNumPerRow',
  APPLICATION_CHART_LAYOUT_INFO = 'pp.applicationChartLayoutInfo',
  AGENT_CHART_LAYOUT_INFO = 'pp.agentChartLayoutInfo',
  LANGUAGE = 'pp.language',
  THEME = 'pp.theme',
  SIDE_NAV_BAR_SCALE = 'pp.sideNavigationBarScale',
  // v3
  AGENT_LIST_SORT = 'pp.agentListSort',
  TRANSACTION_LIST_RESIZABLE = 'pp.transactionListResizable',
  TRANSACTION_DETAIL_RESIZABLE = 'pp.transactionDetailResizable',
  SCATTER_Y_AXIS_MIN_MAX = 'pp.scatterYAxisMinMax',
  HEATMAP_SETTING = 'pp.heatmapSetting',
  SERVER_MAP_HORIZONTAL_RESIZABLE = 'pp.serverMapHorizontalResizable',
  REALTIME_ACTIVE_REQUEST_RESIZABLE = 'pp.realtimeActiveRequestResizable',
  CONFIG_LAST_SELECTED_APPLICATION = 'pp.configLastSelectedApplication',
  SERVER_MAP_CHART_TYPE = 'pp.serverMapChartType',
  INSPECTOR_RESIZABLE = 'pp.inspectorResizable',
  URL_STATISTIC_RESIZABLE = 'pp.urlStatisticResizable',
  ERROR_ANALYSIS_RESIZABLE = 'pp.errorAnalysisResizable',
  OPEN_TELEMETRY_METRIC_RESIZABLE = 'pp.openTelemetryMetricResizable',
  SYSTEM_METRIC_RESIZABLE = 'pp.systemMetricResizable',
}
