export enum APP_SETTING_KEYS {
  FAVORLIITE_APPLICATION_LIST = 'favoriteApplicationList',
  TIMEZONE = 'timezone',
  DATE_FORMAT = 'dateFormat',
  SPLIT_SIZE = 'splitSize',
  LAYER_HEIGHT = 'layerHeight',
  USER_DEFAULT_INBOUND = 'userDefaultInbound',
  USER_DEFAULT_OUTBOUND = 'userDefaultOutbound',
  USER_DEFAULT_PERIOD = 'userDefaultPeriod',
  TRANSACTION_LIST_GUTTER_POSITION = 'transactionListGutterPosition',
  CHART_NUM_PER_ROW = 'chartNumPerRow',
  APPLICATION_CHART_LAYOUT_INFO = 'applicationChartLayoutInfo',
  AGENT_CHART_LAYOUT_INFO = 'agentChartLayoutInfo',
  LANGUAGE = 'language',
  THEME = 'theme',
  SIDE_NAV_BAR_SCALE = 'sideNavigationBarScale',
  // v3
  AGENT_LIST_SORT = 'agentListSort',
  TRANSACTION_LIST_RESIZABLE = 'transactionListResizable',
  TRANSACTION_DETAIL_RESIZABLE = 'transactionDetailResizable',
  SCATTER_Y_AXIS_MIN_MAX = 'scatterYAxisMinMax',
  SERVER_MAP_HORIZONTAL_RESIZABLE = 'serverMapHorizontalResizable',
  REALTIME_ACTIVE_REQUEST_RESIZABLE = 'realtimeActiveRequestResizable',
  CONFIG_LAST_SELECTED_APPLICATION = 'configLastSelectedApplication',
}
