# Defined in commandlineArgument of agent-test pom.xml

server:
  port: 18080

spring:
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /