const PROXY_CONFIG = [
    {
        context: [
            "/api/configuration",
            "/api/serverTime",
            "/api/userConfiguration",
            "/api/applications",
            "/api/getServerMapData",
            "/api/getServerMapDataV2",
            "/api/getResponseTimeHistogramDataV2",
            "/api/getLinkTimeHistogramData",
            "/api/getFilteredServerMapDataMadeOfDotGroup",
            "/api/getDetailedAgentInfo",
            "/api/getAgentList",
            "/api/getAgentStat/jvmGc/chart",
            "/api/getAgentStat/cpuLoad/chart",
            "/api/getAgentStat/transaction/chart",
            "/api/getAgentStat/activeTrace/chart",
            "/api/getAgentStat/responseTime/chart",
            "/api/getAgentStat/dataSource/chartList",
            "/api/getAgentStat/totalThreadCount/chart",
            "/api/getAgentStat/loadedClass/chart",
            "/api/getApplicationStat/memory/chart",
            "/api/getApplicationStat/cpuLoad/chart",
            "/api/getApplicationStat/transaction/chart",
            "/api/getApplicationStat/activeTrace/chart",
            "/api/getApplicationStat/responseTime/chart",
            "/api/getApplicationStat/dataSource/chart",
            "/api/getApplicationStat/totalThreadCount/chart",
            "/api/getApplicationStat/loadedClass/chart",
            "/api/getAgentStatusTimeline",
            "/api/getAgentEvents",
            "/api/getAgentInfo",
            "/api/transactionmetadata",
            "/api/transactionInfo",
            "/api/transactionTimelineInfo",
            "/api/sqlBind",
            "/api/jsonBind",
            "/api/getScatterData",
            "/api/agent/activeThreadLightDump",
            "/api/agent/activeThreadDump",
            "/api/getAgentInstallationInfo",
            "/api/isAvailableApplicationName",
            "/api/isAvailableAgentId",
            "/api/userGroup",
            "/api/user",
            "/api/userGroup/member",
            "/api/application/alarmRule/checker",
            "/api/application/alarmRule",
            "/api/getAgentStat/fileDescriptor/chart",
            "/api/getApplicationStat/fileDescriptor/chart",
            "/api/getAgentStat/directBuffer/chart",
            "/api/getApplicationStat/directBuffer/chart",
            "/api/admin/removeAgentId",
            "/api/admin/removeInactiveAgents",
            "/api/bind",
            "/api/heatmap/drag",
            "/api/traceViewerData",
            "/api/application/webhook",
            "/api/application/webhookSendInfo",
            "/api/application/alarmRule/includeWebhooks",
            "/api/systemMetric/hostGroup",
            "/api/systemMetric/hostGroup/host",
            "/api/systemMetric/hostGroup/host/collectedMetricInfo",
            "/api/systemMetric/hostGroup/host/collectedMetricInfoV2",
            "/api/systemMetric/hostGroup/host/collectedTags",
            "/api/systemMetric/hostGroup/host/collectedMetricData",
            "/api/getApdexScore",
            "/api/getApplicationStat/apdexScore/chart",
            "/api/getAgentStat/apdexScore/chart",
            "/api/uriStat/top50",
            "/api/uriStat/chart",
            "/api/agents/search-all",
            "/api/agents/search-application",
            "/api/agents/statistics",
            "/api/uriStat/summary"
        ],
        target: 'http://localhost:8080',
        secure: false
    },
    {
        context: [
            "/api/agent/activeThread"
        ],
        target: "http://localhost:8080",
        secure: false,
        ws: true
    }
]

module.exports = PROXY_CONFIG;