/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("pinpoint.java8-conventions")
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-webflux:2.4.1")
    implementation("org.springframework.boot:spring-boot-autoconfigure:2.4.1")
}

description = "pinpoint-spring-webflux-plugin-testweb"
