/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("pinpoint.toolchain.java7")
}

dependencies {
    compileOnly(project(":pinpoint-bootstrap-core"))
    compileOnly("org.apache.hbase:hbase-shaded-client:1.2.12")
    compileOnly("commons-logging:commons-logging:1.2")
}

description = "pinpoint-hbase-plugin"
