### save from, to variable
GET http://localhost:8080/serverTime
Accept: application/json
content-type: application/json

> {%
   client.global.set("from", JSON.parse(JSON.stringify(response.body))['currentServerTime'])
   client.global.set("to", JSON.parse(JSON.stringify(response.body))['currentServerTime'] + 100000)
%}


### LongMetric, w/o tags, w/o interval
GET http://{{host}}/systemMetric/chart.pinpoint
    ?hostGroupName={{hostGroupName}}&hostName={{metric-host}}
    &metricName=mem&fieldName=used
    &from={{from}}&to={{to}}
Accept: application/json


### LongMetric, w/o tags, w/o interval
GET http://{{host}}/systemMetric/chart.pinpoint
    ?hostGroupName={{hostGroupName}}&hostName={{metric-host}}
    &metricName=mem&fieldName=used&tags=cpu:cpu1
    &from={{from}}&to={{to}}
Accept: application/json


### LongMetric, w/o tags, with interval
GET http://{{host}}/systemMetric/chart.pinpoint
    ?hostGroupName={{hostGroupName}}&hostName={{metric-host}}
    &metricName=mem&fieldName=free
    &from={{from}}&to={{to}}
    &timeUnit=SECONDS&timeSize=30
Accept: application/json

### DoubleMetric, w/o tags, with interval
GET http://{{host}}/systemMetric/chart.pinpoint
    ?hostGroupName={{hostGroupName}}&hostName={{metric-host}}
    &metricName=cpu&fieldName=usage_user
    &from={{from}}&to={{to}}
    &timeUnit=MINUTES&timeSize=10
Accept: application/json

### DoubleMetric, with tags, with interval
GET http://{{host}}/systemMetric/chart.pinpoint
    ?hostGroupName={{hostGroupName}}&hostName={{metric-host}}
    &metricName=cpu&fieldName=usage_user&tags=cpu:cpu1
    &from={{from}}&to={{to}}
    &timeUnit=MINUTES&timeSize=3
Accept: application/json

### with multiple tags > wrong behavior
GET http://{{host}}/systemMetric/chart.pinpoint
    ?hostGroupName={{hostGroupName}}&hostName={{metric-host}}
    &metricName=disk&fieldName=used_percent&tags=device:disk1s4,fstype:apfs,mode:rw,path:/private/var/vm
    &from={{from}}&to={{to}}
    &timeUnit=SECONDS&timeSize=40
Accept: application/json

### Cpu tag for Mem query
GET http://{{host}}/systemMetric/chart.pinpoint
    ?hostGroupName={{hostGroupName}}&hostName={{metric-host}}
    &metricName=disk&fieldName=used_percent&tags=cpu:cpu1
    &from={{from}}&to={{to}}
    &timeUnit=MINUTES&timeSize=5
Accept: application/json

### No Such Metric
GET http://{{host}}/systemMetric/chart.pinpoint{{metric-host}}
    ?hostGroupName={{hostGroupName}}&hostName={{metric-host}}
    &metricName=mem&fieldName=freer
    &from={{from}}&to={{to}}
Accept: application/json

### Lowercase timeUnit
GET http://{{host}}/systemMetric/chart.pinpoint
    ?hostGroupName={{hostGroupName}}&hostName={{metric-host}}
    &metricName=cpu&fieldName=usage_user&tags=cpu:cpu1
    &from={{from}}&to={{to}}
    &timeUnit=minutes&timeSize=3
Accept: application/json

### Wrong timeUnit
GET http://{{host}}/systemMetric/chart.pinpoint
    ?hostGroupName={{hostGroupName}}&hostName={{metric-host}}
    &metricName=disk&fieldName=used_percent&tags=cpu:cpu1
    &from={{from}}&to={{to}}
    &timeUnit=MINS&timeSize=5
Accept: application/json

### Invalid timeSize
GET http://{{host}}/systemMetric/chart.pinpoint
    ?hostGroupName={{hostGroupName}}&hostName={{metric-host}}
    &metricName=disk&fieldName=used_percent&tags=cpu:cpu1
    &from={{from}}&to={{to}}
    &timeUnit=MINUTES&timeSize=0
Accept: application/json


###
GET http://{{host}}/systemMetric/hostGroup.pinpoint
Accept: application/json


###
GET http://{{host}}/systemMetric/hostGroup/host/collectedMetricInfo.pinpoint
    ?hostGroupName={{hostGroupName}}&hostName={{metric-host}}
Accept: application/json


###
GET http://{{host}}/systemMetric/hostGroup/host/collectedMetricData.pinpoint
    ?hostGroupName={{hostGroupName}}&hostName={{metric-host}}&metricDefinitionId=cpu
    &from={{from}}&to={{to}}
Accept: application/json
###
