### LongMetric, w/o tags
GET http://{{host}}/systemMetric/list.pinpoint
    ?applicationName={{applicationName}}&hostName={{metric-host}}
    &metricName=mem&fieldName=used&from=1620273984000&to=1620274584000
Accept: application/json

### LongMetric, w/o tags
GET http://{{host}}/systemMetric/list.pinpoint
    ?applicationName={{applicationName}}&hostName={{metric-host}}
    &metricName=mem&fieldName=free&from=1612245100000&to=1612246100000
Accept: application/json


### DoubleMetric, w/o tags
GET http://{{host}}/systemMetric/list.pinpoint
    ?applicationName={{applicationName}}&hostName={{metric-host}}
    &metricName=cpu&fieldName=usage_user&from=1612245100000&to=1612245400000
Accept: application/json

### DoubleMetric, with tags
GET http://{{host}}/systemMetric/list.pinpoint
    ?applicationName={{applicationName}}&hostName={{metric-host}}
    &metricName=cpu&fieldName=usage_user&tags=cpu:cpu0&from=1612245100000&to=1612245700000
Accept: application/json

### No Such Metric
GET http://{{host}}/systemMetric/list.pinpoint
    ?applicationName={{applicationName}}&hostName={{metric-host}}
    &metricName=mem&fieldName=freer&from=1612245100000&to=1612247100000
Accept: application/json

###

