/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("pinpoint.toolchain.java7")
}

dependencies {
    api(project(":pinpoint-common-servlet"))
    testImplementation(project(":pinpoint-profiler"))
    testImplementation(project(":pinpoint-profiler-logging"))
    testImplementation(project(":pinpoint-profiler-test"))
    testImplementation(project(":pinpoint-test"))
    testImplementation("org.apache.commons:commons-lang3")
    compileOnly(project(":pinpoint-bootstrap-core"))
    compileOnly("org.jboss.as:jboss-as-security:7.2.0.Final")
}

description = "pinpoint-jboss-plugin"
