# Defined in commandlineArgument of agent-test pom.xml

server:
  port: 18080

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /

spring:
  redis:
    host: localhost
    port: 32912
