# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Frontend-test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 22.13.1
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'

      - name: Install yarn & test
        working-directory: ./web-frontend/src/main/v3
        run: yarn install && yarn test
