/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("pinpoint.java-conventions")
}

dependencies {
    api(project(":pinpoint-bootstrap-core"))
}

description = "pinpoint-process-plugin"
